srms/urls.py
from dashboard import views
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('results/', include('results.urls')),
    path('subjects/', include('subjects.urls')),
    path('students/', include('students.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('classes/', include('student_classes.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

students/urls.py
from django.urls import path

from students.views import (
    StudentCreateView, StudentListView, StudentUpdateView, StudentDeleteView
)


app_name = 'students'

urlpatterns = [
    path('', StudentListView.as_view(), name='student_list'),
    path('create/', StudentCreateView.as_view(), name='student_create'),
    path('update/<int:pk>', StudentUpdateView.as_view(), name='student_update'),
    path('delete/<int:pk>', StudentDeleteView.as_view(), name='student_delete'),
]

subjects/urls.py
from django.urls import path
from .views import (
    SubjectCreateView, SubjectListView, SubjectUpdateView, SubjectDeleteView,
    SubjectCombinationCreateView, SubjectCombinationListView, SubjectCombinationUpdateView, SubjectCombinationDeleteView
)

app_name = 'subjects'

urlpatterns = [
    path('', SubjectListView.as_view(), name='subject_list'),
    path('create/', SubjectCreateView.as_view(), name='create_subject'),
    path('update/<int:pk>/', SubjectUpdateView.as_view(), name='update_subject'),
    path('delete/<int:pk>/', SubjectDeleteView.as_view(), name='delete_subject'),

    # SubjectConbinations
    path('combination/create/', SubjectCombinationCreateView.as_view(), name='create_subject_combination' ),
    path('combination/list/', SubjectCombinationListView.as_view(), name='subject_combination_list' ),
    path('combination/update/<int:pk>', SubjectCombinationUpdateView.as_view(), name='subject_combination_update' ),
    path('combination/delete/<int:pk>', SubjectCombinationDeleteView.as_view(), name='subject_combination_delete' ),
]

students/models.py
from django.db import models
from student_classes.models import StudentClass
from django.urls import reverse
from datetime import date
# Create your models here.

class Student(models.Model):
    select_gender = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other'),
    )

    student_name = models.CharField(max_length=100)
    student_roll = models.IntegerField(unique=True)
    student_email = models.EmailField()
    student_gender = models.CharField(max_length=8, choices=select_gender)
    student_class = models.ForeignKey(StudentClass, on_delete=models.CASCADE)
    student_date_of_birth = models.DateField(default=date.today())
    student_reg = models.DateField(auto_now_add=True, auto_now=False)

    def get_absolute_url(self):
        return reverse('students:student_create')

    def __str__(self):
        return self.student_name

students/forms.py
from django import forms
from students.models import Student

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'
        exclude = ['student_reg']
        widgets = {
            'student_name'  :   forms.TextInput(attrs={'class':'form-control'}),
            'student_roll'  :   forms.NumberInput(attrs={'class':'form-control'}),
            'student_email'  :   forms.EmailInput(attrs={'class':'form-control'}),
            'student_gender'  :   forms.Select(attrs={'class':'form-control'}),
            'student_class'  :   forms.Select(attrs={'class':'form-control'}),
            'student_date_of_birth'  :   forms.DateInput(attrs={'class':'form-control'}),
        }

students/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from .models import Student
from .forms import StudentForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


class StudentCreateView(LoginRequiredMixin, CreateView):
    model = Student
    form_class = StudentForm

    def get_context_data(self, **kwargs):
        context = super(StudentCreateView, self).get_context_data(**kwargs)
        context['main_page_title'] = 'Student Creation'
        context['panel_name'] = 'Students'
        context['panel_title'] = 'Create Student'
        return context

class StudentListView(LoginRequiredMixin, ListView):
    model = Student
    field_list = [
        'Student Name', 'Roll No', 'Class', 'Reg Date', 'Date of birth'
    ]
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['main_page_title'] = 'Manage Students'
        context['panel_name']   =   'Students'
        context['panel_title']  =   'View Students Info'
        context['field_list']   =   self.field_list
        return context

class StudentUpdateView(LoginRequiredMixin, UpdateView):
    model = Student
    template_name_suffix = '_form'
    form_class = StudentForm
    success_url = reverse_lazy('students:student_list')

    def get_context_data(self, **kwargs):
        context = super(StudentUpdateView, self).get_context_data(**kwargs)
        context['main_page_title'] = 'Update Student Info'
        context['panel_name'] = 'Students'
        context['panel_title'] = 'Update Student info'
        return context

class StudentDeleteView(LoginRequiredMixin, DeleteView):
    model = Student
    template_name_suffix = '_delete'
    success_url = reverse_lazy('students:student_list')

    def get_context_data(self, **kwargs):
        context = super(StudentDeleteView, self).get_context_data(**kwargs)
        context['main_page_title'] = 'Student Delete Confirmation'
        context['panel_name'] = 'Students'
        context['panel_title'] = 'Delete Student'
        return context

students/templates/students/student_delete.html
{% extends 'base.html' %}


{% block main_page_title %}
{{ main_page_title }}
{% endblock main_page_title %}


{% block breadcumb %}
<li><a href="{% url 'students:student_list' %}">{{ panel_name }}</a></li>
<li class="active">{{ panel_title }}</li>
{% endblock breadcumb %}

{% block panel %}
<div class="col-md-8 col-md-offset-2">
    <div class="panel">
        <div class="panel-heading">
            <div class="panel-title">
                <h5>{{ panel_title }}</h5>
            </div>
        </div>
        <div class="panel-body">
            <form method="post" class="form">{% csrf_token %}
                <h2>Are you sure you want to delete student "{{ object }}" info ?</h2>
                <input type="submit" value="Confirm" class="btn btn-danger">
            </form>
        </div>
    </div>
</div>
{% endblock panel %}

students/templates/students/student_form.html
{% extends 'base.html' %}

{% block main_page_title %}
{{ main_page_title }}
{% endblock main_page_title %}

{% block breadcumb %}
<li><a href="{% url 'students:student_list' %}">{{ panel_name }}</a></li>
<li class="active">{{ panel_title }}</li>
{% endblock breadcumb %}

{% block panel %}
{% include 'includes/form_panel.html' %}
{% endblock panel %}


{% block javascript_code %}
    
{% endblock javascript_code %}
    

students/templates/students/student_list.html
{% extends 'base.html' %}

{% block main_page_title %}
{{ main_page_title }}
{% endblock main_page_title %}

{% block breadcumb %}
<li><a href="{% url 'subjects:subject_list' %}">{{ panel_name }}</a></li>
<li class="active">{{ panel_title }}</li>
{% endblock breadcumb %}

{% block panel_title %}
{{ panel_title }}
{% endblock panel_title %}

{% block panel %}
{% include 'includes/manage_panel_top.html' %}
{% for object in object_list %}
<tr role="row" class="odd">
    <td class="">{{ object.id }}</td>
    <td>{{ object.student_name }}</td>
    <td>{{ object.student_roll }}</td>
    <td>{{ object.student_class }}</td>
    <td>{{ object.student_reg }}</td>
    <td>{{ object.student_date_of_birth }}</td>
    <td>
        <a href="{% url 'students:student_update' object.id %}" class="btn btn-primary"><i class="fa fa-edit" title="Edit Record"></i>
        </a>
        <a href="{% url 'students:student_delete' object.id %}" class="btn btn-danger"><i class="fa fa-trash" title="Delete Record"></i>
        </a>

    </td>
</tr>
{% endfor %}
{% include 'includes/manage_panel_bottom.html' %}
{% endblock panel %}


{% block javascript_code %}
<script>
</script>
{% endblock javascript_code %}