dashboard/urls.py
from django.urls import path
from dashboard import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('find-result/', views.find_result_view, name='find_result'),
    path('change-password/', views.PasswordChangeView.as_view(), name='change_password'),
    path('find-result/<int:pk>/result/', views.result, name='get_result'),
]

results/urls.py
from django.urls import path, re_path
from results import views

app_name = 'results'

urlpatterns = [
    path('declare/', views.declare_result_view, name='declare_result'),
    path('update/<int:pk>/', views.result_update_view, name='update_result'),
    path('delete/<int:pk>/', views.result_delete_view, name='delete_result'),
    # path('declare/class_based/', views.DeclareResultCreateView.as_view(), name='declare_result'),
    path('list/', views.DeclareResultListView.as_view(), name='result_list'),
    path('declare/validate/', views.validate_data, name='validate_data'),
    path('declare/setup/', views.setup_update_view, name='setup'),
]

srms/urls.py
from dashboard import views
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('results/', include('results.urls')),
    path('subjects/', include('subjects.urls')),
    path('students/', include('students.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('classes/', include('student_classes.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

students/urls.py
from django.urls import path

from students.views import (
    StudentCreateView, StudentListView, StudentUpdateView, StudentDeleteView
)


app_name = 'students'

urlpatterns = [
    path('', StudentListView.as_view(), name='student_list'),
    path('create/', StudentCreateView.as_view(), name='student_create'),
    path('update/<int:pk>', StudentUpdateView.as_view(), name='student_update'),
    path('delete/<int:pk>', StudentDeleteView.as_view(), name='student_delete'),
]

subjects/urls.py
from django.urls import path
from .views import (
    SubjectCreateView, SubjectListView, SubjectUpdateView, SubjectDeleteView,
    SubjectCombinationCreateView, SubjectCombinationListView, SubjectCombinationUpdateView, SubjectCombinationDeleteView
)

app_name = 'subjects'

urlpatterns = [
    path('', SubjectListView.as_view(), name='subject_list'),
    path('create/', SubjectCreateView.as_view(), name='create_subject'),
    path('update/<int:pk>/', SubjectUpdateView.as_view(), name='update_subject'),
    path('delete/<int:pk>/', SubjectDeleteView.as_view(), name='delete_subject'),

    # SubjectConbinations
    path('combination/create/', SubjectCombinationCreateView.as_view(), name='create_subject_combination' ),
    path('combination/list/', SubjectCombinationListView.as_view(), name='subject_combination_list' ),
    path('combination/update/<int:pk>', SubjectCombinationUpdateView.as_view(), name='subject_combination_update' ),
    path('combination/delete/<int:pk>', SubjectCombinationDeleteView.as_view(), name='subject_combination_delete' ),
]

templates/snipets/footer_static_files.html
{% load static %}

<!-- ========== COMMON JS FILES ========== -->
<script src="{% static 'js/jquery/jquery-2.2.4.min.js' %}"></script>
<script src="{% static 'js/jquery-ui/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'js/pace/pace.min.js' %}"></script>
<script src="{% static 'js/lobipanel/lobipanel.min.js' %}"></script>
<script src="{% static 'js/iscroll/iscroll.js' %}"></script>

<!-- ========== PAGE JS FILES ========== -->
<script src="{% static 'js/prism/prism.js' %}"></script>
<script src="{% static 'js/DataTables/datatables.min.js' %}"></script>
<script src="{% static 'js/waypoint/waypoints.min.js' %}"></script>
<script src="{% static 'js/counterUp/jquery.counterup.min.js' %}"></script>
<script src="{% static 'js/amcharts/amcharts.js' %}"></script>
<script src="{% static 'js/amcharts/serial.js' %}"></script>
<script src="{% static 'js/amcharts/plugins/export/export.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'js/amcharts/plugins/export/export.css' %}" type="text/css" media="all" />
<script src="{% static 'js/amcharts/themes/light.js' %}"></script>
<script src="{% static 'js/toastr/toastr.min.js' %}"></script>
<script src="{% static 'js/icheck/icheck.min.js' %}"></script>

<!-- ========== THEME JS ========== -->
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/production-chart.js' %}"></script>
<script src="{% static 'js/traffic-chart.js' %}"></script>
<script src="{% static 'js/task-list.js' %}"></script>

<!-- ========== ADD custom.js FILE BELOW WITH YOUR CHANGES ========== -->

templates/snipets/header_static_files.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Admin Login</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'css/animate-css/animate.min.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'css/prism/prism.css' %}" media="screen"> <!-- USED FOR DEMO HELP - YOU CAN REMOVE IT -->
    <link rel="stylesheet" type="text/css" href="{% static 'js/DataTables/datatables.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" media="screen">
    <script src="{% static 'js/modernizr/modernizr.min.js' %}"></script>

    
    {% block internerl_css %}
        <style>
            .errorWrap {
                padding: 10px;
                margin: 0 0 20px 0;
                background: #fff;
                border-left: 4px solid #dd3d36;
                -webkit-box-shadow: 0 1px 1px 0 rgba(0, 0, 0, .1);
                box-shadow: 0 1px 1px 0 rgba(0, 0, 0, .1);
            }
        
            .succWrap {
                padding: 10px;
                margin: 0 0 20px 0;
                background: #fff;
                border-left: 4px solid #5cb85c;
                -webkit-box-shadow: 0 1px 1px 0 rgba(0, 0, 0, .1);
                box-shadow: 0 1px 1px 0 rgba(0, 0, 0, .1);
            }
        </style>
    {% endblock internerl_css %}

    
    {% block top_js %}
        
    {% endblock top_js %}
        
        
</head>

templates/snipets/nav.html
<nav class="navbar top-navbar bg-white box-shadow">
    <div class="container-fluid">
        <div class="row">
            <div class="navbar-header no-padding">
                <a class="navbar-brand" href="{% url 'dashboard:dashboard' %}">
                    Mygrades | Admin
                </a>
                <span class="small-nav-handle hidden-sm hidden-xs"><i class="fa fa-outdent"></i></span>
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1"
                    aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <i class="fa fa-ellipsis-v"></i>
                </button>
                <button type="button" class="navbar-toggle mobile-nav-toggle">
                    <i class="fa fa-bars"></i>
                </button>
            </div>
            <!-- /.navbar-header -->

            <div class="collapse navbar-collapse" id="navbar-collapse-1">
                <ul class="nav navbar-nav" data-dropdown-in="fadeIn" data-dropdown-out="fadeOut">
                    <li class="hidden-sm hidden-xs"><a href="#" class="user-info-handle"><i class="fa fa-user"></i></a></li>
                    <li class="hidden-sm hidden-xs"><a href="#" class="full-screen-handle"><i class="fa fa-arrows-alt"></i></a></li>

                    <li class="hidden-xs hidden-xs">
                        <!-- <a href="#">My Tasks</a> -->
                    </li>

                </ul>
                <!-- /.nav navbar-nav -->

                <ul class="nav navbar-nav navbar-right" data-dropdown-in="fadeIn" data-dropdown-out="fadeOut">


                    <li><a href="{% url 'logout' %}" class="color-danger text-center"><i class="fa fa-sign-out"></i>
                            Logout</a></li>



                </ul>
                <!-- /.nav navbar-nav navbar-right -->
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</nav>

templates/snipets/sidebar_nav.html
<div class="sidebar-nav">
    <ul class="side-nav color-gray">
        <li class="nav-header">
            <span class="">Main Category</span>
        </li>
        <li>
            <a href="{% url 'dashboard:dashboard' %}"><i class="fa fa-dashboard"></i> <span>Dashboard</span> </a>

        </li>

        <li class="nav-header">
            <span class="">Appearance</span>
        </li>
        <li class="has-children">
            <a href="#"><i class="fa fa-file-text"></i> <span>Student Classes</span> <i class="fa fa-angle-right arrow"></i></a>
            <ul class="child-nav">
                <li><a href="{% url 'student_classes:create_class' %}"><i class="fa fa-bars"></i> <span>Create Class</span></a></li>
                <li><a href="{% url 'student_classes:class_list' %}"><i class="fa fa fa-server"></i> <span>Manage
                            Classes</span></a></li>

            </ul>
        </li>
        <li class="has-children">
            <a href="{% url 'subjects:subject_list' %}"><i class="fa fa-file-text"></i> <span>Subjects</span> <i class="fa fa-angle-right arrow"></i></a>
            <ul class="child-nav">
                <li><a href="{% url 'subjects:create_subject' %}"><i class="fa fa-bars"></i> <span>Create
                            Subject</span></a></li>
                <li><a href="{% url 'subjects:subject_list' %}"><i class="fa fa fa-server"></i> <span>Manage
                            Subjects</span></a></li>
                <li><a href="{% url 'subjects:create_subject_combination' %}"><i class="fa fa-newspaper-o"></i>
                        <span>Add Subject Combination </span></a></li>
                <a href="{% url 'subjects:subject_combination_list' %}"><i class="fa fa-newspaper-o"></i>
                    <span>Manage Subject Combination </span></a>
        </li>
    </ul>
    </li>
    <li class="has-children">
        <a href="{% url 'students:student_list' %}"><i class="fa fa-users"></i> <span>Students</span> <i class="fa fa-angle-right arrow"></i></a>
        <ul class="child-nav">
            <li><a href="{% url 'students:student_create' %}"><i class="fa fa-bars"></i> <span>Add Students</span></a></li>
            <li><a href="{% url 'students:student_list' %}"><i class="fa fa fa-server"></i> <span>Manage
                        Students</span></a></li>

        </ul>
    </li>
    <li class="has-children">
        <a href="#"><i class="fa fa-info-circle"></i> <span>Result</span> <i class="fa fa-angle-right arrow"></i></a>
        <ul class="child-nav">
            <li><a href="{% url 'results:declare_result' %}"><i class="fa fa-bars"></i> <span>Add Result</span></a></li>
            <li><a href="{% url 'results:result_list' %}"><i class="fa fa fa-server"></i> <span>Manage
                        Result</span></a></li>

        </ul>
    <li><a href="{% url 'dashboard:change_password' %}"><i class="fa fa fa-server"></i> <span> Admin Change
                Password</span></a></li>

    </li>
</div>