srms/urls.py
from dashboard import views
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('results/', include('results.urls')),
    path('subjects/', include('subjects.urls')),
    path('students/', include('students.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('classes/', include('student_classes.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

subjects/urls.py
from django.urls import path
from .views import (
    SubjectCreateView, SubjectListView, SubjectUpdateView, SubjectDeleteView,
    SubjectCombinationCreateView, SubjectCombinationListView, SubjectCombinationUpdateView, SubjectCombinationDeleteView
)

app_name = 'subjects'

urlpatterns = [
    path('', SubjectListView.as_view(), name='subject_list'),
    path('create/', SubjectCreateView.as_view(), name='create_subject'),
    path('update/<int:pk>/', SubjectUpdateView.as_view(), name='update_subject'),
    path('delete/<int:pk>/', SubjectDeleteView.as_view(), name='delete_subject'),

    # SubjectConbinations
    path('combination/create/', SubjectCombinationCreateView.as_view(), name='create_subject_combination' ),
    path('combination/list/', SubjectCombinationListView.as_view(), name='subject_combination_list' ),
    path('combination/update/<int:pk>', SubjectCombinationUpdateView.as_view(), name='subject_combination_update' ),
    path('combination/delete/<int:pk>', SubjectCombinationDeleteView.as_view(), name='subject_combination_delete' ),
]

subjects/models.py
from django.db import models
from django.urls import reverse
from student_classes.models import StudentClass

# Create your models here.

class Subject(models.Model):
    subject_name = models.CharField(max_length=100)
    subject_code = models.IntegerField()
    subject_creation_date = models.DateTimeField(auto_now=False, auto_now_add=True)
    subject_update_date = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.subject_name
    
    def get_absolute_url(self):
        return reverse('subjects:subject_list')



class SubjectCombination(models.Model):
    select_class = models.ForeignKey(StudentClass, on_delete=models.CASCADE)
    select_subject = models.ForeignKey(Subject, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('subjects:subject_combination_list')

    def __str__(self):
        return '%s Section-%s'%(self.select_class.class_name, self.select_class.section)
    

subjects/forms.py
from django.forms import ModelForm
from django import forms
from .models import Subject, SubjectCombination

class SubjectForm(ModelForm):
    class Meta:
        model = Subject
        fields = ['subject_name', 'subject_code']
        widgets = {
            'subject_name': forms.TextInput(attrs={'class': 'form-control'}),
            'subject_code':  forms.NumberInput(attrs={'class': 'form-control'}),
        }

class SubjectCombinationForm(ModelForm):
    class Meta:
        model = SubjectCombination
        fields = ['select_class', 'select_subject']
        widgets = {
            'select_class': forms.Select(
                attrs={
                    'class': 'form-control'
                    }
                ),
            'select_subject':  forms.Select(
                attrs={
                    'class': 'form-control'
                    }
                ),
        }

subjects/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Subject, SubjectCombination
from .forms import SubjectForm, SubjectCombinationForm
from django.urls import reverse_lazy
# Create your views here.



class SubjectCreateView(LoginRequiredMixin, CreateView):
    model = Subject
    form_class = SubjectForm
    
    def get_context_data(self, **kwargs):
        context = super(SubjectCreateView, self).get_context_data(**kwargs)
        context['main_page_title'] = 'Subject Creation'
        context['panel_name'] = 'Subjects'
        context['panel_title'] = 'Add Subject'
        return context

class SubjectListView(LoginRequiredMixin, ListView):
    model = Subject
    field_list = [
        'Subject Name', 'Subject Code', 'Creation Date', 'Last Updated'
    ]
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['main_page_title'] = 'Manage Subjects'
        context['panel_name']   =   'Subjects'
        context['panel_title']  =   'View Subjects Info'
        context['field_list']   =   self.field_list
        return context

class SubjectUpdateView(LoginRequiredMixin,UpdateView):
    model = Subject
    template_name_suffix = '_form'
    form_class = SubjectForm
    success_url = reverse_lazy('subjects:subject_list')

class SubjectDeleteView(LoginRequiredMixin, DeleteView):
    model = Subject
    template_name_suffix = '_delete'
    success_url = reverse_lazy('subjects:subject_list')

    
    def get_context_data(self, **kwargs):
        context = super(SubjectDeleteView, self).get_context_data(**kwargs)
        context['main_page_title'] = 'Subject Delete Confirmation'
        context['panel_name'] = 'Subjects'
        context['panel_title'] = 'Delete Subject'
        return context
    
class SubjectCombinationCreateView(LoginRequiredMixin, CreateView):
    model = SubjectCombination
    form_class = SubjectCombinationForm
    template_name_suffix = '_form'

    def get_context_data(self, **kwargs):
        context = super(SubjectCombinationCreateView, self).get_context_data(**kwargs)
        context['main_page_title'] = 'SubjectCombination Creation'
        context['panel_name'] = 'SubjectConbinations'
        context['panel_title'] = 'Create SubjectConbination'
        return context

class SubjectCombinationListView(LoginRequiredMixin, ListView):
    model = SubjectCombination
    field_list = [
        'Class', 'Section', 'Subject'
    ]
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['main_page_title'] = 'Manage SubjectCombinations'
        context['panel_name']   =   'SubjectCombinations'
        context['panel_title']  =   'View SubjectCombinations Info'
        context['field_list']   =   self.field_list
        return context

class SubjectCombinationUpdateView(LoginRequiredMixin, UpdateView):
    model = SubjectCombination
    template_name_suffix = '_form'
    form_class = SubjectCombinationForm
    success_url = reverse_lazy('subjects:subject_combination_list')

class SubjectCombinationDeleteView(LoginRequiredMixin, DeleteView):
    model = SubjectCombination
    template_name_suffix = "_delete"
    success_url = reverse_lazy('subjects:subject_combination_list')

    def get_context_data(self, **kwargs):
        context = super(SubjectCombinationDeleteView, self).get_context_data(**kwargs)
        context['main_page_title'] = 'SubjectCombination Delete Confirmation'
        context['panel_name'] = 'SubjectCombinations'
        context['panel_title'] = 'Delete SubjectCombination'
        return context

subjects/templates/subjects/subject_delete.html
{% extends 'base.html' %}


{% block main_page_title %}
{{ main_page_title }}
{% endblock main_page_title %}


{% block breadcumb %}
<li><a href="{% url 'subjects:subject_list' %}">{{ panel_name }}</a></li>
<li class="active">{{ panel_title }}</li>
{% endblock breadcumb %}


{% block panel %}
<div class="col-md-8 col-md-offset-2">
    <div class="panel">
        <div class="panel-heading">
            <div class="panel-title">
                <h5>{{ panel_title }}</h5>
            </div>
        </div>
        <div class="panel-body">
            <form method="post" class="form">{% csrf_token %}
            <h2>Are you sure you want to delete subject combination "{{ object }}" info ?</h2>
            <input type="submit" value="Confirm" class="btn btn-danger">
            </form>
        </div>
    </div>
</div>
{% endblock panel %}

subjects/templates/subjects/subject_form.html
{% extends 'base.html' %}

{% block main_page_title %}
{{ main_page_title }}
{% endblock main_page_title %}

{% block breadcumb %}
<li><a href="{% url 'subjects:subject_list' %}">{{ panel_name }}</a></li>
<li class="active">{{ panel_title }}</li>
{% endblock breadcumb %}

{% block panel %}
{% include 'includes/form_panel.html' %}
{% endblock panel %}

subjects/templates/subjects/subject_list.html
{% extends 'base.html' %}

{% block main_page_title %}
{{ main_page_title }}
{% endblock main_page_title %}

{% block breadcumb %}
<li><a href="{% url 'subjects:subject_list' %}">{{ panel_name }}</a></li>
<li class="active">{{ panel_title }}</li>
{% endblock breadcumb %}

{% block panel_title %}
{{ panel_title }}
{% endblock panel_title %}

{% block panel %}
{% include 'includes/manage_panel_top.html' %}
{% for object in object_list %}
<tr role="row" class="odd">
    <td class="">{{ object.id }}</td>
    <td>{{ object.subject_name }}</td>
    <td>{{ object.subject_code }}</td>
    <td>{{ object.subject_creation_date }}</td>
    <td>{{ object.subject_update_date }}</td>
    <td>
        <a href="{% url 'subjects:update_subject' object.id %}" class="btn btn-primary"><i class="fa fa-edit" title="Edit Record"></i>
        </a>
        <a href="{% url 'subjects:delete_subject' object.id %}" class="btn btn-danger"><i class="fa fa-trash" title="Delete Record"></i>
        </a>

    </td>
</tr>
{% endfor %}
{% include 'includes/manage_panel_bottom.html' %}
{% endblock panel %}


{% block javascript_code %}
<script>
   
</script>
{% endblock javascript_code %}

subjects/templates/subjects/subjectcombination_delete.html
{% extends 'base.html' %}


{% block main_page_title %}
{{ main_page_title }}
{% endblock main_page_title %}


{% block breadcumb %}
<li><a href="{% url 'subjects:subject_list' %}">{{ panel_name }}</a></li>
<li class="active">{{ panel_title }}</li>
{% endblock breadcumb %}


{% block panel %}
<div class="col-md-8 col-md-offset-2">
    <div class="panel">
        <div class="panel-heading">
            <div class="panel-title">
                <h5>{{ panel_title }}</h5>
            </div>
        </div>
        <div class="panel-body">
            <form method="post" class="form">{% csrf_token %}
                <h2>Are you sure you want to delete subject combination "{{ object }}" info ?</h2>
                <input type="submit" value="Confirm" class="btn btn-danger">
            </form>
        </div>
    </div>
</div>
{% endblock panel %}

subjects/templates/subjects/subjectcombination_form.html
{% extends 'base.html' %}


{% block main_page_title %}
{{ main_page_title }}
{% endblock main_page_title %}


{% block breadcumb %}
<li><a href="{% url 'subjects:subject_combination_list' %}">{{ panel_name }}</a></li>
<li class="active">{{ panel_title }}</li>
{% endblock breadcumb %}


{% block panel %}
{% include 'includes/form_panel.html' %}
{% endblock panel %}

subjects/templates/subjects/subjectcombination_list.html
{% extends 'base.html' %}

{% block main_page_title %}
{{ main_page_title }}
{% endblock main_page_title %}

{% block breadcumb %}
<li><a href="{% url 'subjects:subject_combination_list' %}">{{ panel_name }}</a></li>
<li class="active">{{ panel_title }}</li>
{% endblock breadcumb %}

{% block panel_title %}
{{ panel_title }}
{% endblock panel_title %}

{% block panel %}
{% include 'includes/manage_panel_top.html' %}
{% for object in object_list %}
<tr role="row" class="odd">
    <td class="">{{ object.id }}</td>
    <td>{{ object.select_class.class_name }}</td>
    <td>{{ object.select_class.section }}</td>
    <td>{{ object.select_subject }}</td>
    <td>
        <a href="{% url 'subjects:subject_combination_update' object.id %}" class="btn btn-primary"><i class="fa fa-edit" title="Edit Record"></i>
        </a>
        <a href="{% url 'subjects:subject_combination_delete' object.id %}" class="btn btn-danger"><i class="fa fa-trash" title="Delete Record"></i>
        </a>

    </td>
</tr>
{% endfor %}
{% include 'includes/manage_panel_bottom.html' %}
{% endblock panel %}


{% block javascript_code %}
<script>
</script>
{% endblock javascript_code %}