dashboard/urls.py
from django.urls import path
from dashboard import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('find-result/', views.find_result_view, name='find_result'),
    path('change-password/', views.PasswordChangeView.as_view(), name='change_password'),
    path('find-result/<int:pk>/result/', views.result, name='get_result'),
]

results/urls.py
from django.urls import path, re_path
from results import views

app_name = 'results'

urlpatterns = [
    path('declare/', views.declare_result_view, name='declare_result'),
    path('update/<int:pk>/', views.result_update_view, name='update_result'),
    path('delete/<int:pk>/', views.result_delete_view, name='delete_result'),
    # path('declare/class_based/', views.DeclareResultCreateView.as_view(), name='declare_result'),
    path('list/', views.DeclareResultListView.as_view(), name='result_list'),
    path('declare/validate/', views.validate_data, name='validate_data'),
    path('declare/setup/', views.setup_update_view, name='setup'),
]

srms/urls.py
from dashboard import views
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('results/', include('results.urls')),
    path('subjects/', include('subjects.urls')),
    path('students/', include('students.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('classes/', include('student_classes.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

student_classes/urls.py
from django.urls import path
from student_classes.views import *

app_name = 'student_classes'

urlpatterns = [
    path('create/', StudentClassCreateView.as_view(), name='create_class'),
    path('update/<int:pk>/', StudentClassUpdateView.as_view(), name='update_class'),
    path('delete/<int:pk>/', StudentClassDeleteView.as_view(), name='delete_class'),
    path('list/', StudentClassListView.as_view(), name='class_list'),
]

students/urls.py
from django.urls import path

from students.views import (
    StudentCreateView, StudentListView, StudentUpdateView, StudentDeleteView
)


app_name = 'students'

urlpatterns = [
    path('', StudentListView.as_view(), name='student_list'),
    path('create/', StudentCreateView.as_view(), name='student_create'),
    path('update/<int:pk>', StudentUpdateView.as_view(), name='student_update'),
    path('delete/<int:pk>', StudentDeleteView.as_view(), name='student_delete'),
]

subjects/urls.py
from django.urls import path
from .views import (
    SubjectCreateView, SubjectListView, SubjectUpdateView, SubjectDeleteView,
    SubjectCombinationCreateView, SubjectCombinationListView, SubjectCombinationUpdateView, SubjectCombinationDeleteView
)

app_name = 'subjects'

urlpatterns = [
    path('', SubjectListView.as_view(), name='subject_list'),
    path('create/', SubjectCreateView.as_view(), name='create_subject'),
    path('update/<int:pk>/', SubjectUpdateView.as_view(), name='update_subject'),
    path('delete/<int:pk>/', SubjectDeleteView.as_view(), name='delete_subject'),

    # SubjectConbinations
    path('combination/create/', SubjectCombinationCreateView.as_view(), name='create_subject_combination' ),
    path('combination/list/', SubjectCombinationListView.as_view(), name='subject_combination_list' ),
    path('combination/update/<int:pk>', SubjectCombinationUpdateView.as_view(), name='subject_combination_update' ),
    path('combination/delete/<int:pk>', SubjectCombinationDeleteView.as_view(), name='subject_combination_delete' ),
]

dashboard/models.py
from django.db import models

# Create your models here.

results/models.py
from django.db import models
from subjects.models import StudentClass
from students.models import Student
from django.urls import reverse
from django.contrib.postgres.fields import JSONField

# Create your models here.

class DeclareResult(models.Model):
    select_class = models.ForeignKey(StudentClass, on_delete=models.CASCADE)
    select_student = models.ForeignKey(Student, on_delete=models.CASCADE)
    marks = JSONField(blank=True)

    def get_absolute_url(self):
        return reverse('results:declare_result')
    def __str__(self):
        return "%s Section-%s" % (self.select_class.class_name, self.select_class.section)

results/forms.py
from django.forms import ModelForm
from django import forms
from .models import DeclareResult

class DeclareResultForm(ModelForm):
    class Meta:
        model = DeclareResult
        fields = ['select_class', 'select_student']
        widgets = {
            'select_class': forms.Select(attrs={'class': 'form-control'}),
            'select_student':  forms.Select(attrs={'class': 'form-control'}),
        }
        labels = {
            'select_class' : 'Class',
            'select_student' : 'Select Student',
        }

dashboard/views.py
from django.template.loader import get_template
from django.http import HttpResponse
from io import BytesIO
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import authenticate, login
from django.views.generic import TemplateView
from django.contrib.auth.models import User
from results.models import DeclareResult
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.core import serializers

from student_classes.models import StudentClass
from results.models import DeclareResult
from subjects.models import Subject
from students.models import Student


def index(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        print("\nUser Name = ", username)
        print("Password = ", password)
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('dashboard:dashboard')
        else:
            context = {'message': 'Invalid User Name and Password'}
            return render(request, 'index.html', context)
    return render(request, 'index.html', {'name': 'Riajul Kashem', 'pass': 'login@srms'})


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "dashboard.html"

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        context['cls'] = StudentClass.objects.count()
        context['results'] = DeclareResult.objects.count()
        context['students'] = Student.objects.count()
        context['subjects'] = Subject.objects.count()
        return context


def find_result_view(request):
    student_class = DeclareResult.objects.all()
    if request.method == "POST":
        data = request.POST
        # data = json.loads(form)
        roll = int(data['rollid'])
        pk = int(data['class'])
        clss = get_object_or_404(DeclareResult, pk=pk)
        if clss.select_student.student_roll == roll:
            data = {
                'pk': data['class']
            }
            return JsonResponse(data)
        else:
            pk = '0'
            data = {
                'pk': pk
            }
            return JsonResponse(data)
    return render(request, 'find_result.html', {'class': student_class})


def result(request, pk):
    object = get_object_or_404(DeclareResult, pk=pk)
    lst = []
    marks = []
    for i in range(int(len(object.marks) / 2)):
        lst.append(object.marks['subject_' + str(i)])
        lst.append(object.marks['subject_' + str(i) + '_mark'])
        marks.append(lst)
        lst = []
    return render(request, 'result.html', {'object': object, 'pk': pk, 'marks': marks})


class PasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    success_url = reverse_lazy('dashboard:dashboard')
    template_name = 'password_change_form.html'

    def get_context_data(self, **kwargs):
        context = super(PasswordChangeView, self).get_context_data(**kwargs)
        context['main_page_title'] = 'Admin Change Password'
        context['panel_title'] = 'Admin Change Password'
        return context

results/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import (
    CreateView, ListView, UpdateView, DeleteView
)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from results.models import DeclareResult
from results.forms import DeclareResultForm
from subjects.models import SubjectCombination
from student_classes.models import StudentClass
from students.models import Student
from django.http import HttpResponse, JsonResponse

from django.core import serializers
import json

# Create your views here.

def validate_data(request):
    smt = SubjectCombination.objects.all()
    data = {}
    if request.method == "GET":
        rc = request.GET['selectedClass']
        subjects = []
        for s in smt:
            if s.select_class.class_name in rc and s.select_class.section in rc:
                subjects.append(s.select_subject)
        sir_subjects = serializers.serialize('json', subjects)
        data['subjects'] = sir_subjects
        return JsonResponse(data)
    subjects = None
    data['result'] = 'you made a request with empty data'
    return HttpResponse(json.dumps(data), content_type="application/json")

def declare_result_view(request):
    context = {}
    if request.method == "POST":
        form = request.POST
        data = json.loads(json.dumps(form))
        data.pop('csrfmiddlewaretoken')
        pk = data['select_class']
        clas = StudentClass.objects.get(id=pk)
        pk = data['select_student']
        student = Student.objects.get(id=pk)
        data.pop('select_class')
        data.pop('select_student')
        DeclareResult.objects.create(select_class=clas, select_student=student, marks=data)
    else:
        form = DeclareResultForm()
        context['main_page_title'] = 'Declare Students Result'
        context['panel_name'] = 'Results'
        context['panel_title'] = 'Declare Result'
        context['form'] = form
    return render(request, "results/declareresult_form.html", context)

def setup_update_view(request):
    data = {}
    if request.method == "GET":
        pk_value = int(request.GET['pk_value'])
        result_obj = get_object_or_404(DeclareResult, pk = pk_value)
        dt = result_obj.marks
        data['dt'] = dt
        return HttpResponse(json.dumps(data), content_type="application/json")
    return HttpResponse(json.dumps(data), content_type="application/json")

@login_required
def result_update_view(request, pk):
    result = get_object_or_404(DeclareResult, pk=pk)
    form = DeclareResultForm(instance=result)
    context = {}
    context['main_page_title'] = 'Update Students Result'
    context['panel_name'] = 'Results'
    context['panel_title'] = 'Update Result'
    context['form'] = form
    context['pk'] = pk
    if request.method == "POST":
        all_data = request.POST
        data = json.loads(json.dumps(all_data))
        data.pop('csrfmiddlewaretoken')
        pk = data['select_class']
        clas = StudentClass.objects.get(id=pk)
        pk = data['select_student']
        student = Student.objects.get(id=pk)
        data.pop('select_class')
        data.pop('select_student')
        print('Modified Data = ', data)
        result.select_class = clas
        result.select_student = student
        result.marks = data
        result.save()
        print('\nResult updated\n')
        return redirect('results:result_list')
    return render(request, "results/update_form.html", context)

@login_required
def result_delete_view(request, pk):
    obj = get_object_or_404(DeclareResult, pk=pk)
    if request.method == "POST":
        obj.delete()
        return redirect('results:result_list')
    return render(request, "results/result_delete.html", {"object":obj})

class DeclareResultListView(LoginRequiredMixin, ListView):
    model = DeclareResult

    field_list = [
        'Student Name', 'Roll No', 'Class', 'Reg Date', 'View Result'
    ]
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['main_page_title'] = 'Manage Results'
        context['panel_name']   =   'Results'
        context['panel_title']  =   'View Results Info'
        context['field_list']   =   self.field_list
        return context
    

dashboard/templates/dashboard.html
{% extends 'base.html' %}

{% block main_page_title %}
    Dashboard
{% endblock main_page_title %}
    

{% block main_page_content %}
    <div class="row">
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <a class="dashboard-stat bg-primary" href="{% url 'students:student_list' %}">
                <span class="number counter">{{ students }}</span>
                <span class="name">Regd Studetns</span>
                <span class="bg-icon"><i class="fa fa-users"></i></span>
            </a>
            <!-- /.dashboard-stat -->
        </div>
        <!-- /.col-lg-3 col-md-3 col-sm-6 col-xs-12 -->
    
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <a class="dashboard-stat bg-danger" href="{% url 'subjects:subject_list' %}">
                <span class="number counter">{{ subjects }}</span>
                <span class="name">Subjects Listed</span>
                <span class="bg-icon"><i class="fa fa-ticket"></i></span>
            </a>
            <!-- /.dashboard-stat -->
        </div>
        <!-- /.col-lg-3 col-md-3 col-sm-6 col-xs-12 -->
    
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <a class="dashboard-stat bg-warning" href="{% url 'student_classes:class_list' %}">
                <span class="number counter">{{ cls }}</span>
                <span class="name">Total classes listed</span>
                <span class="bg-icon"><i class="fa fa-bank"></i></span>
            </a>
            <!-- /.dashboard-stat -->
        </div>
        <!-- /.col-lg-3 col-md-3 col-sm-6 col-xs-12 -->
    
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <a class="dashboard-stat bg-success" href="{% url 'results:result_list' %}">
                <span class="number counter">{{ results }}</span>
                <span class="name">Results Declared</span>
                <span class="bg-icon"><i class="fa fa-file-text"></i></span>
            </a>
            <!-- /.dashboard-stat -->
        </div>
        <!-- /.col-lg-3 col-md-3 col-sm-6 col-xs-12 -->
    </div>
    <!-- /.row -->
{% endblock main_page_content %}

{% block javascript_code %}
    <script>
        $(function () {
            // Counter for dashboard stats
            $('.counter').counterUp({
                delay: 10,
                time: 1000
            });

            // Welcome notification
            toastr.options = {
                "closeButton": true,
                "debug": false,
                "newestOnTop": false,
                "progressBar": false,
                "positionClass": "toast-top-right",
                "preventDuplicates": false,
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "timeOut": "5000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            }
            toastr["success"]("Welcome to student Result Management System!");
        });
    </script>
{% endblock javascript_code %}

dashboard/templates/find_result.html
{% extends 'base.html' %}

{% block main_wrapper %}
<div class="login-bg-color bg-black-300">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel login-box">
                <div class="panel-heading">
                    <div class="panel-title text-center">
                        <h4>Student Grade Management System</h4>
                    </div>
                    <div id="query_alert"></div>
                </div>
                <div class="panel-body p-20">
                    <form class="query-form" method="post"> {% csrf_token %}
                        <div class="form-group">
                            <label for="rollid">Enter your Roll Id</label>
                            <input type="text" class="form-control" id="rollid" placeholder="Enter Your Roll Id"
                                autocomplete="off" name="rollid">
                        </div>
                        <div class="form-group">
                            <label for="class">Class</label>
                            <select name="class" class="form-control" id="class" required="required">
                                <option value="">Select Class</option>
                                {% for cls in class %}
                                <option value="{{ cls.id }}">{{ cls }}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <div class="form-group mt-20">
                            <div class="">
                                <button type="submit" class="btn btn-success btn-labeled pull-right">Search<span
                                        class="btn-label btn-label-right"><i class="fa fa-check"></i></span></button>
                                <div class="clearfix"></div>
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <a href="{% url 'home' %}">Back to Home</a>
                        </div>
                    </form>

                    <hr>
                </div>
            </div>
            <!-- /.panel -->
            <p class="text-muted text-center"><small>Copyright © <a>Naadesh Borra</a> 2024</small></p>
        </div>
        <!-- /.col-md-6 col-md-offset-3 -->
    </div>
    <!-- /.row -->
</div>
<!-- /. -->
{% endblock main_wrapper %}

{% block javascript_code %}
<script>
    $(document).ready(function(){
        console.log("Document Ready")
        var myForm = $('.query-form')
        myForm.submit(function(e){
            e.preventDefault()
            var formData = $(this).serialize()
            console.log(formData)
            $.ajax({
                method: "POST",
                url: window.location.href,
                data: formData,
                success: function (json) {
                    if (json.pk === '0') {
                        alert("No Result Found With This Roll No and Class Name\nTry valid one")
                    } else {
                        window.location = '/dashboard/find-result/' + json.pk + '/result/'
                    }
                },
                error: function(error){
                    alert("Oops!! Error")
                }
            })
        })
    })
</script>
{% endblock javascript_code %}

dashboard/templates/index.html
{% extends 'base.html' %}


{% block main_wrapper %}
    
    <div class="">
        <div class="row">
            <h1 align="center">MyGrades.com</h1>
            <h2 align="center"> Student Grade Mangement System</h2>
            <div class="col-lg-6 visible-lg-block">

                <section class="section">
                    <div class="row mt-40">
                        <div class="col-md-10 col-md-offset-1 pt-50">

                            <div class="row mt-30 ">
                                <div class="col-md-11">
                                    <div class="panel">
                                        <div class="panel-heading">
                                            <div class="panel-title text-center">
                                                <h4>For Students</h4>
                                            </div>
                                        </div>
                                        <div class="panel-body p-20">

                                            <div class="section-title">
                                                <p class="sub-title">Student Grade Management System</p>
                                            </div>
                                            
                                            <form class="form-horizontal" method="post">
                                                <div class="form-group">
                                                    <label for="inputEmail3" class="col-sm-6 control-label">Search
                                                        your result</label>
                                                    <div class="col-sm-6">
                                                        <a href="{% url 'dashboard:find_result' %}">click here</a>
                                                    </div>
                                                </div>

                                            </form>




                                        </div>
                                    </div>
                                    <!-- /.panel -->

                                </div>
                                <!-- /.col-md-11 -->
                            </div>
                            <!-- /.row -->
                        </div>
                        <!-- /.col-md-12 -->
                    </div>
                    <!-- /.row -->
                </section>
            </div>
            <div class="col-lg-6">
                <section class="section">
                    <div class="row mt-40">
                        <div class="col-md-10 col-md-offset-1 pt-50">

                            <div class="row mt-30 ">
                                <div class="col-md-11">
                                    <div class="panel">
                                        <div class="panel-heading">
                                            <div class="panel-title text-center">
                                                <h4>Admin Login </h4>
                                            </div>
                                        </div>
                                        <div class="panel-body p-20">

                                            <div class="section-title">
                                                <p class="sub-title">Student Grade Management System</p>
                                            </div>

                                            <form class="form-horizontal" method="post"> {% csrf_token %}
                                                <div class="alert alert-danger" role="alert">
                                                    {{ message }}
                                                </div>
                                                <div class="form-group">
                                                    <label for="inputEmail3" class="col-sm-2 control-label">Name:</label>
                                                    <div class="col-sm-10">
                                                        <input type="text" name="username" class="form-control" id="inputEmail3"
                                                            placeholder="UserName">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
                                                    <div class="col-sm-10">
                                                        <input type="password" name="password" class="form-control" id="inputPassword3"
                                                            placeholder="Password">
                                                    </div>
                                                </div>

                                                <div class="form-group mt-20">
                                                    <div class="col-sm-offset-2 col-sm-10">

                                                        <button type="submit" name="login" class="btn btn-success btn-labeled pull-right">Sign
                                                            in<span class="btn-label btn-label-right"><i class="fa fa-check"></i></span></button>
                                                    </div>
                                                </div>
                                            </form>




                                        </div>
                                    </div>
                                    <!-- /.panel -->
                                </div>
                                <!-- /.col-md-11 -->
                            </div>
                            <!-- /.row -->
                        </div>
                        <!-- /.col-md-12 -->
                    </div>
                    <!-- /.row -->
                </section>

            </div>
            <!-- /.col-md-6 -->
        </div>
        <!-- /.row -->
    </div>
    
{% endblock main_wrapper %}
    

dashboard/templates/password_change_form.html
{% extends 'base.html' %}
    
{% block main_page_title %}
{{ main_page_title }}
{% endblock main_page_title %}

{% block breadcumb %}
<li class="active">{{ panel_title }}</li>
{% endblock breadcumb %}

{% block panel %}
{% include 'includes/form_panel.html' %}
{% endblock panel %}

dashboard/templates/result.html
{% extends 'base.html' %}

{% block main_wrapper %}
    <div class="container-fluid" style="background-color:#e1edfa">
        <div class="row text-center d-block">
            <h2 class="text-primary bold pb-25"><a href="{% url 'home' %}">Student Result Management System</a></h2>
        </div>
        <h4 style="text-align:right"><a href="{% url 'dashboard:pdf' id=object.id %}" target="_blank">Save as PDF</a></h4>
        <div class="container" id="marksheet">
            <p>
                <b>Student Name     : </b>  {{ object.select_student.student_name | safe }}
            </p>
            <p>
                <b>Student Class    : </b>  {{ object.select_class.class_name }}   ( <b>{{ object.select_class.section | safe }}</b> )
            </p>
            <p>
                <b>Student Roll : </b> {{ object.select_student.student_roll | safe }}
            </p>
            <h2 class="text-center text-primary">Mark Sheet</h2>
            
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Subject Name</th>
                        <th scope="col">Mark</th>
                    </tr>
                </thead>
                <tbody id="table-row">
                    {% for mark in marks %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            
                            {% for m in mark %}
                                <td>{{ m }}</td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        
        <div class="shadow-lg p-3">
            <span class="link"><a href="{% url 'home' %}">Back To Home</a></span>
        </div>
    </div>   
{% endblock main_wrapper %}